"""Add category to incomes

Revision ID: 09f6089291df
Revises: '60e765acdf1f'
Create Date: 2025-07-21 18:49:32.909321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09f6089291df'
down_revision = '60e765acdf1f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###