"""Initial migration

Revision ID: 35f5c2949c55
Revises: '8f90f0bf3372'
Create Date: 2025-07-21 18:15:44.661657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35f5c2949c55'
down_revision = '8f90f0bf3372'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###