"""Add category to incomes

Revision ID: 60e765acdf1f
Revises: '35f5c2949c55'
Create Date: 2025-07-21 18:48:38.686157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60e765acdf1f'
down_revision = '35f5c2949c55'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incomes', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'incomes', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'incomes', type_='foreignkey')
    op.drop_column('incomes', 'category_id')
    # ### end Alembic commands ###