"""Initial migration

Revision ID: 8f90f0bf3372
Revises: 'a242b6032373'
Create Date: 2025-07-21 18:15:26.814366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f90f0bf3372'
down_revision = 'a242b6032373'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###