"""add limit to expense category

Revision ID: c443cb982127
Revises: 'bb3cd02ade12'
Create Date: 2025-08-03 16:19:59.793132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c443cb982127'
down_revision = 'bb3cd02ade12'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense_categories', sa.Column('limit', sa.Float(), nullable=True))
    op.drop_constraint(op.f('expenses_category_id_fkey'), 'expenses', type_='foreignkey')
    op.create_foreign_key(None, 'expenses', 'expense_categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('incomes_category_id_fkey'), 'incomes', type_='foreignkey')
    op.create_foreign_key(None, 'incomes', 'income_categories', ['category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'incomes', type_='foreignkey')
    op.create_foreign_key(op.f('incomes_category_id_fkey'), 'incomes', 'income_categories', ['category_id'], ['id'])
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.create_foreign_key(op.f('expenses_category_id_fkey'), 'expenses', 'expense_categories', ['category_id'], ['id'])
    op.drop_column('expense_categories', 'limit')
    # ### end Alembic commands ###