"""Add category_id to incomes table

Revision ID: <your_new_revision_id>
Revises: a242b6032373
Create Date: 2025-07-22 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'revid7'
down_revision = 'a242b6032373'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incomes', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_incomes_category_id_categories', 'incomes', 'categories', ['category_id'], ['id'])
    op.create_index(op.f('ix_incomes_category_id'), 'incomes', ['category_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incomes_category_id'), table_name='incomes')
    op.drop_constraint('fk_incomes_category_id_categories', 'incomes', type_='foreignkey')
    op.drop_column('incomes', 'category_id')
    # ### end Alembic commands ###
